# Generated by Django 4.1 on 2023-03-12 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Routesetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ZoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        choices=[
                            ("Z1", "Zone 1"),
                            ("Z2", "Zone 2"),
                            ("Z3", "Zone 3"),
                            ("Z4", "Zone 4"),
                            ("Z5", "Zone 5"),
                            ("Z6", "Zone 6"),
                            ("Z7", "Zone 7"),
                            ("Z8", "Zone 8"),
                            ("Z9", "Zone 9"),
                            ("Z10", "Zone 10"),
                            ("Z11", "Zone 11"),
                            ("Z12", "Zone 12"),
                            ("Z13", "Zone 13"),
                            ("Z14", "Zone 14"),
                            ("Z15", "Zone 15"),
                            ("Z16", "Zone 16"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoulderProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Black", "Black"),
                            ("Blue", "Blue"),
                            ("Orange", "Orange"),
                            ("Pink", "Pink"),
                            ("Green", "Green"),
                            ("Yellow", "Yellow"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (0, "V0"),
                            (1, "V1"),
                            (2, "V2"),
                            (3, "V3"),
                            (4, "V4"),
                            (5, "V5"),
                            (6, "V6"),
                            (7, "V7"),
                            (8, "V8"),
                            (9, "V9"),
                            (10, "V10"),
                            (11, "V11"),
                        ]
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "setter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="tracker.routesetter",
                    ),
                ),
                (
                    "zone_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone",
                        to="tracker.zonemodel",
                    ),
                ),
            ],
        ),
    ]
