# Generated by Django 4.1 on 2023-03-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_zonemodel_zone_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boulderproblem",
            options={"ordering": ("grade",)},
        ),
    ]
