# Generated by Django 4.1 on 2023-03-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_boulderproblem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulderproblem",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
